---
title: "Analisis Descriptivo"
author: "Daniel Escobar David"
date: "30/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
rm(list=ls())
library(dplyr)
library(ggplot2)

datos <- read.csv2("./DatosCSVProcesados/Datos.csv")
```

# Pre-Procesamiento De Los Datos

## NAs por fila

```{r}
NAs <- apply(datos, 2, is.na)
apply(NAs, 2, sum)
```


```{r}
variables_categoricas <- datos %>% 
  select(Sexo.Jefe,Sexo.Conyuge,Tipo.Union,Region,Energia,Trabajo.Jefe,Trabajo.conyuge,Edu.Jefe,Edu.Conyuge,Edad.Conyuge,Estrato.vivienda) %>% 
  mutate_if(is.numeric,as.factor)

variables_numericas <- datos %>% 
  select(-c(Sexo.Jefe,Sexo.Conyuge,Tipo.Union,Region,Energia,Trabajo.Jefe,Trabajo.conyuge,Edu.Jefe,Edu.Conyuge,Edad.Conyuge,Estrato.vivienda))

datos <- cbind(variables_numericas,variables_categoricas)
```

```{r}
library(ggplot2)

ggplot(datos,aes(x=Tipo.Union,y=Hijos))+geom_boxplot()
ggplot(datos,aes(y=Edad.Jefe,x=factor(Hijos)))+geom_boxplot()
```

```{r}
test <- glm(factor(Hijos)~Tipo.Union, family="poisson", data=datos)
```

