---
title: "modelos_caret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions, include=FALSE}
library(caret)
library(tidyr)
library(dplyr)
library(ggplot2)

set.seed(42)

# Utilidades
data_split <- function(datos,split){
  if(missing(split)){
    split<-0.7
  }
  trainIndex <- createDataPartition(datos$Hijos, p=split, list=FALSE)
  datos_tr <- datos[ trainIndex,]
  datos_vl <- datos[-trainIndex,]
  return(list("entrenamiento" = datos_tr, "validacion" = datos_vl))
}

confusion_matrix <- function(modelo,datos){
  modelo_prediccion <- predict(modelo,newdata = datos )
  print(confusionMatrix(modelo_prediccion, datos$Hijos ))
}


evaluate_model <-function(modelo,datos_vl){
  predicciones <- predict(modelo,newdata = datos_vl)
}

#Modelos
rf <- function(datos_tr,datos_tr_x){
  mtry <- sqrt(ncol(datos_tr_x))
  tunegrid <- expand.grid(.mtry=mtry)
  ctrl <- trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
  rf_fit <-train(Hijos ~ ., data = datos_tr, method = "rf", preProcess = c("center","scale"), tuneGrid   = tunegrid,trControl = ctrl)
  return(rf_fit)
}

rf_variable_selection <-function(datos_tr,datos_tr_x,sizes){
  rfe_control <- rfeControl(functions = rfFuncs,
                      method = "repeatedcv",
                      repeats = 5, 
                      number = 10)
  rf_select <- rfe(x = datos_tr_x, 
                   y = datos_tr$Hijos, 
                   sizes = sizes,
                   rfeControl = rfe_control)
  return(rf_select)
}



```

#Creacion del modelo seleccionado : Random Forest Regressor
## Lectura de los datos


```{r}
datos_completos <- read.csv2("./DatosCSVProcesados/DatosCompletosING.csv")
datos_completos$Codigo <- NULL
summary(datos_completos)

```

```{r}
variables_categoricas <- datos_completos %>% 
  select(Sexo.Jefe,Sexo.Conyuge,Tipo.Union,Region,Estrato.vivienda,Trabajo.Jefe,Trabajo.conyuge,Uso.tecnologia.Jefe,Uso.tecnologia.conyuge,Edu.Jefe,Edu.Conyuge,Afiliacion.salud) %>% 
  mutate_if(is.numeric,as.factor)

variables_numericas <- datos_completos %>% 
  select(-c(Sexo.Jefe,Sexo.Conyuge,Tipo.Union,Region,Estrato.vivienda,Trabajo.Jefe,Trabajo.conyuge,Uso.tecnologia.Jefe,Uso.tecnologia.conyuge,Edu.Jefe,Edu.Conyuge,Afiliacion.salud))


summary(variables_categoricas)
summary(variables_numericas)
```
### Tratamiento de nulos

```{r}
replace_factor_na_categorico <- function(x){
  x <- as.character(x)
  x <- if_else(is.na(x), "noconyuge", x)
  x <- as.factor(x)
}





variables_categoricas_sin_nulos <- data.frame(variables_categoricas)
variables_categoricas_sin_nulos <- variables_categoricas_sin_nulos %>%mutate_if(is.factor, replace_factor_na_categorico)

variables_numericas_sin_nulos <- data.frame(variables_numericas)
for(i in 1:ncol(variables_numericas_sin_nulos)){
  variables_numericas_sin_nulos[is.na(variables_numericas_sin_nulos[,i]), i] <- mean(variables_numericas_sin_nulos[,i], na.rm = TRUE)
}

summary(variables_categoricas_sin_nulos)
summary(variables_numericas_sin_nulos)

```


### Datos de validacion y de entrenamiento
```{r}
datos_completos_codificados <- as.data.frame(cbind(variables_numericas_sin_nulos,variables_categoricas_sin_nulos))
summary(datos_completos_codificados)


particion <- data_split(datos_completos_codificados)
datos_tr <- particion$entrenamiento
datos_tr_x <- subset(datos_tr, select = -c(Hijos))
datos_vl <- particion$validacion
```



## Creacion del modelo RF
### Seleccion de las variables mas importantes

```{r}

rf_best_variables<-rf_variable_selection(datos_tr,datos_tr_x,c(5,6,7))
print(rf_best_variables)

importancia_variables <- data.frame(variable = row.names(varImp(rf_best_variables))[1:7],
                        importancia = varImp(rf_best_variables)[1:7, 1])

ggplot(data = importancia_variables, 
       aes(x = reorder(variable, -importancia), y = importancia, fill = variable)) +
  geom_bar(stat="identity") + labs(x = "Variables", y = "Importancia de la variable") + 
  geom_text(aes(label = round(importancia, 2)), vjust=1.6, color="white", size=4) + 
  theme_bw() + theme(legend.position = "none")

```





```{r}

rf_best_variables_completo<-rf_variable_selection(datos_tr,datos_tr_x,4:14)
print(rf_best_variables_completo)

importancia_variables_completo <- data.frame(variable = row.names(varImp(rf_best_variables_completo))[1:7],
                        importancia = varImp(rf_best_variables_completo)[1:7, 1])

ggplot(data = importancia_variables_completo, 
       aes(x = reorder(variable, -importancia), y = importancia, fill = variable)) +
  geom_bar(stat="identity") + labs(x = "Variables", y = "Importancia de la variable") + 
  geom_text(aes(label = round(importancia, 2)), vjust=1.6, color="white", size=4) + 
  theme_bw() + theme(legend.position = "none")

```










```{r}
#saveRDS(rf_modelo_pareja, "./Modelos/rf_pareja_hijos0-1.rds")
#saveRDS(rf_modelo_solteros, "./Modelos/rf_solteros_hijos0-1.rds")
saveRDS(rf_modelo_pareja_clasificacion_general,"./Modelos/rf_pareja_clasification_general.rds")
```


