---
title: "modelos_caret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions, include=FALSE}
library(caret)
library(tidyr)
library(dplyr)
library(ggplot2)

set.seed(42)

# Utilidades
data_split <- function(datos,split){
  if(missing(split)){
    split<-0.7
  }
  trainIndex <- createDataPartition(datos$Hijos, p=split, list=FALSE)
  datos_tr <- datos[ trainIndex,]
  datos_vl <- datos[-trainIndex,]
  return(list("entrenamiento" = datos_tr, "validacion" = datos_vl))
}

confusion_matrix <- function(modelo,datos){
  modelo_prediccion <- predict(modelo,newdata = datos )
  print(confusionMatrix(modelo_prediccion, datos$Hijos ))
}


evaluate_model <-function(modelo,datos_vl){
  predicciones <- predict(modelo,newdata = datos_vl)
}

rf_creacion_modelo <- function(datos_tr,datos_tr_x){
  ctrl <- trainControl(method="cv", number=3, search="grid")
  #mtry <- sqrt(ncol(datos_tr_x))
  #tunegrid <- expand.grid(.mtry=1:15)
  mtry <- ncol(datos_tr_x)/3
  tunegrid <- expand.grid(.mtry=mtry)
  rf_model <- train(Hijos ~ .,
                     data = datos_tr,
                     method = 'rf',
                     tuneGrid  = tunegrid, 
                     trControl = ctrl)
  return(rf_model)

}

ridge_creacion_modelo <- function(datos_tr){
  parameters <- c(seq(0.01, 0.1, 0.01), seq(0.1, 2, by =0.1) , seq(2, 5, 0.5) )
  ridge<-train(Hijos ~ .,
                data = datos_tr,
                method = 'glmnet', 
                tuneGrid = expand.grid(alpha = 0, lambda = parameters),
                metric =  "Rsquared"
           )
  return(ridge)
}


knn_creacion_modelo <- function(datos_tr){
  ctrl <- trainControl(method="repeatedcv",repeats = 3) #,classProbs=TRUE,summaryFunction = twoClassSummary)
  knnFit <- train(Hijos ~ ., data = datos_tr, method = "knn", trControl = ctrl, preProcess = c("center","scale"),
                  tuneGrid = data.frame(k = 1:10))
  return(knnFit)
}


```

#Creacion del modelo seleccionado : Random Forest Regressor
## Lectura de los datos


```{r}
datos_completos <- read.csv2("./DatosCSVProcesados/DatosCompletosING.csv")
datos_completos$Codigo <- NULL
summary(datos_completos)

```

```{r}
variables_categoricas <- datos_completos %>% 
  select(Sexo.Jefe,Tipo.Union,Trabajo.Jefe,Uso.tecnologia.Jefe,Edu.Jefe) %>% 
  mutate_if(is.numeric,as.factor)

variables_numericas <- datos_completos %>% 
  select(c(Hijos,Edad.Jefe,Cantidad.de.personas,Ingresos.totales,Valor.Electricidad))


summary(variables_categoricas)
summary(variables_numericas)
```


### Datos de validacion y de entrenamiento
```{r}
datos_completos_codificados <- as.data.frame(cbind(variables_numericas,variables_categoricas))
summary(datos_completos_codificados)


particion <- data_split(datos_completos_codificados)
datos_tr <- particion$entrenamiento
datos_tr_x <- subset(datos_tr, select = -c(Hijos))
datos_vl <- particion$validacion
```



## Creacion del modelo RF

```{r}
rf_modelo<-rf_creacion_modelo(datos_tr,datos_tr_x)
print(rf_modelo)
```

## Creacion del modelo Ridge


```{r}
ridge_modelo<-ridge_creacion_modelo(datos_tr)
print(ridge_modelo)
```
## Modelo KNN
```{r}
knn_modelo<-knn_creacion_modelo(datos_tr)
print(knn_modelo)
```


```{r}
saveRDS(rf_modelo,"./Modelos/rf_modelo.rds")
saveRDS(ridge_modelo,"./Modelos/ridge_modelo.rds")
```


